services:
  _defaults:
    autowire: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['app.command']

  Fulll\:
    resource: '../src/*'

  MicroKernel:
    class: \MicroKernel
    public: true
    arguments:
      - !tagged_iterator app.command

